### ISSUE TITLE
デザイン変更

### ISSUE THREAD

**Issue by waspryo** [AkariYamaguchi/rails-hw#5]

**Comment by waspryo** [comment]
俺からのレビューもらってプルリクマージされたら下にあるClose and commentボタンを押してissueをcloseしよう！

**Comment by AkariYamaguchi** [comment]
# 概要（what?）
topの画像とフォントのデザイン変更。

### 画像イメージ
<img width="950" alt="スクリーンショット 2020-01-05 13 19 12" src="https://user-images.githubusercontent.com/54671960/71775083-09078180-2fbe-11ea-8876-85c8242944af.png">


# やること
- [ ] 参考となるサイト探し
イメージではグラデションを使ったサイト

- [ ] イメージに合う画像探し

- [ ] フォント
